version: '2'

networks:
    front_default:
          external: true

services:

    nginx:
        image: nginx:1.13
        volumes:
            - ./www:/code
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./log/nginx:/var/log/nginx
        networks:
            - front_default

    php:
        build: 
            context: ./php
        depends_on:
            - nginx
        volumes:
            - ./www:/code
        networks:
            - front_default
