version: '2'

services:

    nginx:
        image: nginx:1.13
        ports:
            - 33388:80
        volumes:
            - ./www:/code
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./log/nginx:/var/log/nginx

    php:
        build: 
            context: ./php
        depends_on:
            - nginx

        volumes:
            - ./www:/code
